---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Download Azure data factory self-hosted integration runtime
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
            [String]
            $url
          )

          Write-Host "Start Microsoft Integration Runtime download"

          $path = "C:\temp"
          If(!(test-path -PathType container $path))
          {
            New-Item -ItemType Directory -Path $path
          }

          $outFile = "$path\IntegrationRuntime.msi"
          $process = Invoke-WebRequest $url -OutFile $outFile
          if ($process.ExitCode -ne 0)
          { 
            throw "Failed to download Microsoft Integration Runtime. Exit code: $($process.ExitCode)"
          }

          Write-Host "Succeed to download Microsoft Integration Runtime"
        parameters:
          url: https://download.microsoft.com/download/E/4/7/E4771905-1079-445B-8BF9-8A1A075D8A10/IntegrationRuntime_5.36.8726.3.msi

    - name: Install ADF self-hosted IR
      ansible.windows.win_powershell:
        script: |
          Write-Host "Start Microsoft Integration Runtime installation"
          
          $path = "C:\temp\IntegrationRuntime.msi"
          $process = Start-Process "msiexec.exe" "/i $path /quiet /passive" -Wait -PassThru
          if ($process.ExitCode -ne 0)
          {
            throw "Failed to install Microsoft Integration Runtime. msiexec exit code: $($process.ExitCode)"
          }
          Start-Sleep -Seconds 30

          Write-Host "Succeed to install Microsoft Integration Runtime"
