---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Download ADF self-hosted IR installer
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
            [String]
            $url
          )

          Write-Host "Starting ADF self-hosted IR download"

          $path = "C:\temp"
          If(!(test-path -PathType container $path))
          {
            New-Item -ItemType Directory -Path $path
          }

          $outFile = "$path\IntegrationRuntime.msi"
          $process = Invoke-WebRequest $url -OutFile $outFile
          if ($process.ExitCode -ne 0)
          { 
            throw "Failed to download ADF self-hosted IR. Exit code: $($process.ExitCode)"
          }

          Write-Host "Completed ADF self-hosted IR download"
        parameters:
          url: https://download.microsoft.com/download/E/4/7/E4771905-1079-445B-8BF9-8A1A075D8A10/IntegrationRuntime_5.36.8726.3.msi

    - name: Install ADF self-hosted IR
      ansible.windows.win_powershell:
        script: |
          Write-Host "Starting ADF self-hosted IR installation"
          
          $path = "C:\temp\IntegrationRuntime.msi"
          $process = Start-Process "msiexec.exe" "/i $path /quiet /passive" -Wait -PassThru
          if ($process.ExitCode -ne 0)
          {
            throw "Failed to install ADF self-hosted IR. msiexec exit code: $($process.ExitCode)"
          }
          Start-Sleep -Seconds 30

          Write-Host "Completed ADF self-hosted IR installation"

    - name: Delete ADF self-hosted IR installer
      ansible.windows.win_powershell:
        script: |
          $process = Remove-Item -Path C:\temp\IntegrationRuntime.msi
          if ($process.ExitCode -ne 0)
          {
            throw "Failed to delete ADF self-hosted IR installer. msiexec exit code: $($process.ExitCode)"
          }

          Write-Host "Deleted ADF self-hosted IR installer"
