image_name             = "strongswan"
resource_group_name    = "managed-images"
location               = "Australia East"
source_image_publisher = "Canonical"
source_image_offer     = "0001-com-ubuntu-server-jammy"
source_image_sku       = "22_04-lts"
source_image_version   = "latest"
vm_size                = "Standard_F2"
